# Generated by Django 3.1.4 on 2021-01-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('country_code', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.TextField(unique=True)),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
