# Generated by Django 3.1.4 on 2021-04-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.IntegerField(default=9425, max_length=4),
            preserve_default=False,
        ),
    ]
