# Generated by Django 3.1.4 on 2021-04-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transaction_pin',
            field=models.IntegerField(),
        ),
    ]
