# Generated by Django 3.1.4 on 2021-01-12 18:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_customermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='location',
            field=django_countries.fields.CountryField(default='NGN', max_length=2),
        ),
    ]
