# Generated by Django 3.1.4 on 2021-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20210427_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transaction_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
