# Generated by Django 3.1.4 on 2021-01-05 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.TextField(max_length=64)),
                ('coin_avatar', models.ImageField(max_length=500, upload_to='Authentication/static/user/avatar')),
            ],
            options={
                'db_table': 'CoinModel',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('account_name', models.CharField(max_length=64)),
                ('cvv', models.IntegerField()),
                ('bvn', models.IntegerField()),
            ],
            options={
                'db_table': 'CreditCard',
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=64)),
                ('balance', models.IntegerField(default=0.0)),
                ('credit_card', models.ManyToManyField(blank=True, to='Wallet.CreditCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WalletModel',
            },
        ),
    ]
