# Generated by Django 3.1.4 on 2021-01-18 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.TextField(max_length=64)),
                ('coin_avatar', models.ImageField(max_length=500, upload_to='Authentication/static/user/avatar')),
            ],
            options={
                'db_table': 'CoinModel',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'CreditCard',
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('security', 'security'), ('send', 'send'), ('receive', 'receive'), ('verify', 'verify')], max_length=10)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.TextField(max_length=64)),
                ('coin_avatar', models.ImageField(max_length=500, upload_to='Authentication/static/market/trade')),
                ('coin_symbol', models.TextField(default='BTC', max_length=64)),
            ],
            options={
                'db_table': 'TradeModel',
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=64)),
                ('balance', models.IntegerField(default=0.0)),
                ('coin', models.ManyToManyField(to='Wallet.CoinModel')),
                ('credit_card', models.ManyToManyField(blank=True, to='Wallet.CreditCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WalletModel',
            },
        ),
        migrations.CreateModel(
            name='VirtualCardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=101)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'VirtualCardModel',
            },
        ),
    ]
