# Generated by Django 3.1.4 on 2021-01-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.TextField(max_length=64)),
                ('coin_avatar', models.ImageField(max_length=500, upload_to='Authentication/static/user/avatar')),
            ],
            options={
                'db_table': 'CoinModel',
            },
        ),
    ]
