# Generated by Django 3.1.4 on 2021-01-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='label',
            field=models.CharField(choices=[('crytocurrency', 'trade'), ('savings', 'savings'), ('groceries', 'groceries'), ('others', 'others')], max_length=64),
        ),
    ]
