# Generated by Django 3.1.4 on 2021-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('security', 'security'), ('send', 'send'), ('receive', 'receive'), ('verify', 'verify')], max_length=10)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
