# Generated by Django 3.1.4 on 2021-01-05 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='account_name',
            new_name='card_name',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='account_no',
            new_name='card_no',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='bvn',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
