# Generated by Django 3.1.4 on 2021-01-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='coin_symbol',
            field=models.TextField(default='BTC', max_length=64),
        ),
    ]
