# Generated by Django 3.1.4 on 2021-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdefinition',
            old_name='prices',
            new_name='last_price',
        ),
        migrations.AddField(
            model_name='networkdefinition',
            name='recent_price',
            field=models.FloatField(default=7.9),
            preserve_default=False,
        ),
    ]
