# Generated by Django 3.1.4 on 2021-01-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_auto_20210105_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(default='Unknown', max_length=64),
        ),
    ]
