# Generated by Django 3.1.4 on 2021-04-24 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wallet', '0002_auto_20210420_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdefinition',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='networkdefinition',
            name='recent_price',
        ),
        migrations.CreateModel(
            name='SendModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=16)),
                ('amount', models.FloatField()),
                ('address', models.CharField(max_length=32)),
                ('is_verify', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
