# Generated by Django 3.1.4 on 2021-04-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_auto_20210424_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmodel',
            name='address',
            field=models.CharField(max_length=64),
        ),
    ]
