# Generated by Django 3.1.4 on 2021-01-07 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wallet', '0003_creditcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmodel',
            name='coin',
            field=models.ManyToManyField(to='Wallet.CoinModel'),
        ),
        migrations.CreateModel(
            name='VirtualCardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=101)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'VirtualCardModel',
            },
        ),
    ]
