# Generated by Django 3.1.4 on 2021-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_auto_20210425_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdefinition',
            name='fee',
            field=models.FloatField(default=7e-06),
            preserve_default=False,
        ),
    ]
