# Generated by Django 3.1.4 on 2021-04-27 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wallet', '0006_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='header',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Authentication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmodel',
            name='tx_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
